- name: Build an image with the command module for a remote docker host
  hosts: localhost
  connection: local

  tasks:
    - name: create a dir if it does not exist
      become: yes
      file:
        path: /opt/test
        state: directory
        # owner: user1
        # group: user1
        mode: '0755'


      #this play copies the Dockerfile to the host in order to build
    - name: Copy directory from playbook to tmp of the docker host
      copy: 
        src: "{{playbook_dir}}/files/"
        dest: "/opt/test"
        # owner: user1
        # group: user1
        mode: '0644'

      #this builds a docker image from an already built up and slightly customized centos7 image
    - name: build the image
      become: yes
      command: docker build -t localspink10/localinotify /opt/test

    - name: start the the container with a command, without docker ansible module
      become: yes
      command: docker run -d --name inotify localspink10/localinotify /opt/scripts/inotify.sh

    # - name: Start a container with a command
    #   docker_container:
    #     name: inotify1
    #     image: test1/test13
    #     command: ["sleep", "infinity"]
      


    # - name: run the site in a docker container
    #   docker:
    #     name: /tmp/
    #     image: "nameofImage:tag"
    #     state: reloaded






